### ISSUE TITLE
java.io.IOException: Cannot run program "adb": error=2, No such file or directory"

### ISSUE THREAD

**Issue by stephenws** [Testinium/MobileDeviceInfo#1]
I am trying to Run code in Android device but I am getting Error " java.io.IOException: Cannot run program "adb": error=2, No such file or directory"
please check Error log: 
https://gist.github.com/stephenws/795d70c7672c5c646a23c55bd9496182
OS: Mac
IDE: Eclipse
Device: Android device

I have given Android sdk path in Project >> Env.

Code: 
@Test
	public void luanchapp() throws Exception
	{
		DeviceInfo deviceInfo = new DeviceInfoImpl(DeviceType.ALL);
		 
		Device device = deviceInfo.getFirstDevice();
		 
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.PLATFORM, device.getDeviceProductName());
		capabilities.setCapability("platformName", device.getDeviceProductName());
		capabilities.setCapability(MobileCapabilityType.VERSION, device.getProductVersion());
		capabilities.setCapability("deviceName", device.getModelNumber());
		capabilities.setCapability("udid", device.getUniqueDeviceID());
		capabilities.setCapability("app", "/Users/Mukesh/Desktop/Test/Android/Test.apk");
		 
		driver = new AppiumDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
	}

**Comment by bahadirustun** [comment]
Open Terminal and "echo $PATH" run command.
and copy all text

Open Eclipse You can right-click on any project in Package Explorer.
Run As -> Run Configurations. And here, in tab Environment -> New...

and the opening "New Environmental Variant"
Name : PATH
Value : "paste the text you copied above here."

**Comment by stephenws** [comment]
@bahadirustun Thanks it works.
