### ISSUE TITLE
Question: How to achieve Parallel Execution

### ISSUE THREAD

**Issue by stephenws** [Testinium/MobileDeviceInfo#2]
I am using Appium for Test Automation
I just want to run Parallel execution with multiple android devices
How to achieve this?

**Comment by zarashima** [comment]
@stephenws : I utilize this library with FreeMaker template to generate a TestNG suite for parallel executions. This approach is used smoothly in my work, so you can refer to my repository here: https://github.com/zarashima/dynamic-capabilities
