### ISSUE TITLE
IOSSIMULATOR not found and iOS Returning NULL

### ISSUE THREAD

**Issue by SvetenV** [Testinium/MobileDeviceInfo#6]
After i added maven dependencies and the repository, i tried using IOSSIMULATOR but kept being red and giving me this error Message " cannot Resolve" so i went ahead and changed it to Android and Pressed the mouse wheel on it and I there were only 3 device types android ios and all nothing more..
![Screen Shot 2019-12-10 at 4 57 35 PM](https://user-images.githubusercontent.com/58739184/70541330-7ff05c80-1b6f-11ea-86a1-cd2944a25cb4.png)

will there be any fix soon for it ?

**Comment by mjordanBetBright** [comment]
Looks like you'll have to compile the project into yours, maven isn't updated

https://github.com/Testinium/MobileDeviceInfo/issues/5#issuecomment-563205125

**Comment by SvetenV** [comment]
if I compile it into my project will the function work properly ? and won't this be a heavy load to my project ? but unless maven gets updated soon , i have no other choice than following your suggestion.

**Comment by bahadirustun** [comment]
@SvetenV I plan to update maven as soon as possible.

**Comment by SvetenV** [comment]
that would be amazing.

**Comment by SaravanaQA** [comment]
@bahadirustun Any update regarding maven update ?

**Comment by SvetenV** [comment]
Looks like you'll have to compile the project

> @bahadirustun Any update regarding maven update ?

**Comment by nickgarkusha** [comment]
Hi @bahadirustun, do you still intend to upload version 2.0 to the Maven repository?

**Comment by bahadirustun** [comment]
version has been updated. You can now use the IOS SIMULATOR.

**Comment by nickgarkusha** [comment]
Fantastic, thanks.
